name: PDF to SVG
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pdf2svg
        run: sudo apt install pdf2svg
      - name: Move PDF and cleanup previous jobs
        run: |
          rm -R dist/svg/* || true
          mkdir -p dist/pdf dist/svg
          mv *.pdf dist/pdf || true
      - name: Convert PDF to PNG (transparent)
        run: |
          cd dist/pdf
          for n in $(ls -xH *.pdf); do pdf2svg $n "../svg/${n%.*}.svg"; done;
          cd ../..
      - name: Commit SVG
        id: commit
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add dist
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "[bot] converted *.pdf -> *.svg (@ `date +'%Y-%m-%d %H:%M:%S'`)"
            echo "push=true" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Push Commit
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Zip the output
      #  run: |
      #    zip -r ttl74_schamatics.zip dist
      #- name: Upload Release
      #  uses: ncipollo/release-action@v1.12.0
      #  with:
      #   artifacts: "ttl74_schamatics.zip"
      #    token: ${{ secrets.GITHUB_TOKEN }}
